#!/usr/bin/env bash
###############################################################################
# COMMON FUNCTIONS
#
# Shared helpers for operational setup scripts.
#
# Comments in this toolkit should explain why, not merely repeat what a command
# already says. The helpers here exist to keep behaviour consistent across
# scripts: root checks, logging, confirmations, backups and managed file writes.
###############################################################################

set -euo pipefail

# common.sh is sourced by scripts in the toolkit root, so BASH_SOURCE[1] points
# to the operational script that imported this library.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[1]}")" && pwd)"
source "${SCRIPT_DIR}/config.sh"

VERBOSE="no"
if [[ "${1:-}" == "--verbose" ]]; then
    VERBOSE="yes"
fi

SCRIPT_NAME="$(basename "${BASH_SOURCE[1]}" .sh)"
TIMESTAMP="$(date +%Y-%m-%d_%H%M%S)"

mkdir -p "${SERVER_ADMIN_LOG_DIR}"          "${SERVER_ADMIN_BACKUP_DIR}"          "${SERVER_ADMIN_DOCS_DIR}"          "${SERVER_ADMIN_MARIADB_DIR}"

LOG_FILE="${SERVER_ADMIN_LOG_DIR}/${SCRIPT_NAME}_${TIMESTAMP}.log"
touch "${LOG_FILE}"
chmod 600 "${LOG_FILE}"

info() {
    echo "[INFO] $*"
    echo "[INFO] $*" >>"${LOG_FILE}"
}

warn() {
    echo "[WARN] $*"
    echo "[WARN] $*" >>"${LOG_FILE}"
}

ok() {
    echo "[OK] $*"
    echo "[OK] $*" >>"${LOG_FILE}"
}

fail() {
    echo "[ERROR] $*" >&2
    echo "[ERROR] $*" >>"${LOG_FILE}"
    echo
    echo "[ERROR] Full log: ${LOG_FILE}"
    echo "[ERROR] Last 40 log lines:"
    tail -n 40 "${LOG_FILE}" || true
    exit 1
}

require_root() {
    if [[ "${EUID}" -ne 0 ]]; then
        cat >&2 <<EOF
[ERROR] This script must be run as root or via sudo.

Reason:
This toolkit modifies system configuration, installs packages,
or changes services that require elevated privileges.

Example:
  sudo ./${SCRIPT_NAME}.sh
EOF
        exit 1
    fi
}

confirm() {
    local prompt="$1"

    if [[ "${INTERACTIVE_CONFIRMATIONS}" != "yes" ]]; then
        return 0
    fi

    read -rp "${prompt} [y/N]: " answer
    [[ "${answer}" =~ ^[Yy]$ ]]
}

run() {
    info "Running: $*"

    if [[ "${VERBOSE}" == "yes" ]]; then
        "$@" 2>&1 | tee -a "${LOG_FILE}"
        local rc=${PIPESTATUS[0]}
        [[ "${rc}" -eq 0 ]] || fail "Command failed: $*"
    else
        "$@" >>"${LOG_FILE}" 2>&1 || fail "Command failed: $*"
    fi
}

backup_file() {
    local file="$1"

    [[ -f "${file}" ]] || return 0

    local safe_name backup_path
    safe_name="$(echo "${file}" | sed 's|^/||; s|/|-|g')_${TIMESTAMP}.bak"
    backup_path="${SERVER_ADMIN_BACKUP_DIR}/${safe_name}"

    cp -a "${file}" "${backup_path}"
    info "Backed up ${file} to ${backup_path}"
}

write_managed_file() {
    local file="$1"
    local mode="$2"
    local owner="$3"
    local temp_file="$4"

    if [[ -f "${file}" ]] && cmp -s "${file}" "${temp_file}"; then
        info "No change needed: ${file}"
        return 0
    fi

    if [[ -f "${file}" ]]; then
        warn "Managed file differs and may be overwritten: ${file}"
        if ! confirm "Overwrite ${file}?"; then
            info "Skipped overwrite: ${file}"
            return 0
        fi
        backup_file "${file}"
    fi

    mkdir -p "$(dirname "${file}")"
    cp "${temp_file}" "${file}"
    chown "${owner}" "${file}"
    chmod "${mode}" "${file}"
    ok "Wrote managed file: ${file}"
}

hostname_to_username() {
    local host="$1"

    echo "${host}"         | tr '[:upper:]' '[:lower:]'         | sed -E 's/[^a-z0-9_]/_/g; s/_+/_/g; s/^_//; s/_$//'
}

validate_hostname() {
    local host="$1"

    [[ "${host}" =~ ^[A-Za-z0-9.-]+$ ]] || fail "Invalid hostname: ${host}"
    [[ "${host}" == *.* ]] || fail "Hostname should be fully-qualified, for example shop.example.com"
}

check_cert_covers_hostname() {
    local cert_file="$1"
    local hostname="$2"
    local base
    base="${hostname#*.}"

    local text
    text="$(openssl x509 -in "${cert_file}" -noout -text)"

    if echo "${text}" | grep -Eq "DNS:${hostname}([,[:space:]]|$)"; then
        return 0
    fi

    if [[ "${hostname}" == *.* ]] && echo "${text}" | grep -Eq "DNS:\*\.${base}([,[:space:]]|$)"; then
        return 0
    fi

    return 1
}

managed_header() {
    local generated_by="$1"

    cat <<EOF
###############################################################################
# MANAGED FILE
#
# Server Setup Toolkit Version: ${SERVER_SETUP_TOOLKIT_VERSION}
# Generated by: ${generated_by}
# Generated at: $(date -Is)
#
# Manual edits may be overwritten by rerunning the setup scripts.
###############################################################################
EOF
}
