#!/usr/bin/env bash
###############################################################################
# FILES HELPERS
#
# Sourced by lib/common.sh. Functions are namespaced because Bash has no real
# module system. These helpers should provide reusable vocabulary; calling
# scripts should own workflow and presentation decisions.
###############################################################################

file_backup() {
    local file="$1"

    [[ -f "${file}" ]] || return 0

    mkdir -p "${SERVER_ADMIN_BACKUP_DIR}"
    local safe_name backup_path
    safe_name="$(echo "${file}" | sed 's|^/||; s|/|-|g')_${TIMESTAMP}.bak"
    backup_path="${SERVER_ADMIN_BACKUP_DIR}/${safe_name}"

    cp -a "${file}" "${backup_path}" || return 1
    log_info "Backed up ${file} to ${backup_path}"
}


file_write_managed() {
    local file="$1"
    local mode="$2"
    local owner_group="$3"
    local temp_file="$4"

    if [[ -f "${file}" ]] && cmp -s "${file}" "${temp_file}"; then
        log_info "No change needed: ${file}"
        return 0
    fi

    if [[ -f "${file}" ]]; then
        log_warn "Managed file differs and may be overwritten: ${file}"
        if ! prompt_confirm "Overwrite ${file}?"; then
            log_info "Skipped overwrite: ${file}"
            return 1
        fi
        file_backup "${file}" || return 1
    fi

    mkdir -p "$(dirname "${file}")" || return 1
    cp "${temp_file}" "${file}" || return 1
    chown "${owner_group}" "${file}" || return 1
    chmod "${mode}" "${file}" || return 1
    log_ok "Wrote managed file: ${file}"
}


file_managed_header() {
    local generated_by="$1"

    cat <<EOF
###############################################################################
# MANAGED FILE
#
# Server Setup Toolkit Version: ${SERVER_SETUP_TOOLKIT_VERSION}
# Generated by: ${generated_by}
# Generated at: $(date -Is)
#
# Manual edits may be overwritten by rerunning the setup scripts.
###############################################################################
EOF
}



file_server_admin_root_permissions_match() {
    local toolkit_root="$1"
    local admin_group="$2"

    [[ -d "${toolkit_root}" ]] || return 1
    [[ "$(stat -c '%U:%G %a' "${toolkit_root}")" == "root:${admin_group} 2770" ]]
}


file_set_server_admin_root_permissions() {
    local toolkit_root="$1"
    local admin_group="$2"

    [[ -d "${toolkit_root}" ]] || return 1
    user_system_group_exists "${admin_group}" || return 1
    chown root:"${admin_group}" "${toolkit_root}" || return 1
    chmod 2770 "${toolkit_root}"
}


file_set_server_admin_directory_permissions() {
    local toolkit_root="$1"
    local admin_group="$2"

    [[ -d "${toolkit_root}" ]] || return 1
    user_system_group_exists "${admin_group}" || return 1

    find "${toolkit_root}"         -path "${SERVER_ADMIN_SSL_DIR}" -prune -o         -type d -exec chown root:"${admin_group}" {} + -exec chmod 2770 {} +
}


file_set_server_admin_script_permissions() {
    local toolkit_root="$1"
    local admin_group="$2"

    [[ -d "${toolkit_root}" ]] || return 1
    user_system_group_exists "${admin_group}" || return 1

    find "${toolkit_root}"         -path "${SERVER_ADMIN_SSL_DIR}" -prune -o         -type f -name "*.sh" -exec chown root:"${admin_group}" {} + -exec chmod 770 {} +
}


file_set_server_admin_regular_file_permissions() {
    local toolkit_root="$1"
    local admin_group="$2"

    [[ -d "${toolkit_root}" ]] || return 1
    user_system_group_exists "${admin_group}" || return 1

    find "${toolkit_root}"         -path "${SERVER_ADMIN_SSL_DIR}" -prune -o         -type f ! -name "*.sh" -exec chown root:"${admin_group}" {} + -exec chmod 660 {} +
}


file_harden_server_admin_ssl_directory() {
    local ssl_dir="${1:-${SERVER_ADMIN_SSL_DIR}}"

    [[ -d "${ssl_dir}" ]] || return 1
    chown root:root "${ssl_dir}" || return 1
    chmod 700 "${ssl_dir}"
}


file_server_admin_ssl_directory_permissions_match() {
    local ssl_dir="${1:-${SERVER_ADMIN_SSL_DIR}}"

    [[ -d "${ssl_dir}" ]] || return 1
    [[ "$(stat -c '%U:%G %a' "${ssl_dir}")" == "root:root 700" ]]
}
